### ISSUE TITLE
Multiple Scrambled word cause confusion

### ISSUE THREAD

**Issue by kk5dire** [DamianSwanAAJHS2/String-Game#1] opened 2021-08-03 20:41 UTC
Words with multiple scrambles can cause confusion and a unfair loss

**Comment by kiyarose** [comment] 2021-08-22 23:21
Gottcha well this repo is no longer updated unless I decide to later which I will notify If the issue is fixed. I will archive the repo and close this now

**Closed as completed by kiyarose** 2021-08-22 23:21 UTC
